version: "3.8"

services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    command: sh -c "npm install && npm run start"
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

  prisma:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: npx prisma studio
    ports:
      - "5555:5555"
    depends_on:
      - db

volumes:
  db_data:
